services:
  rmq:
    image: rabbitmq:3-management-alpine
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_VHOST=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    healthcheck:
      test: [ 'CMD', 'rabbitmq-diagnostics', '-q', 'ping' ]
      start_period: 4s
      interval: 5s
      timeout: 1s
      retries: 1

  camera:
    image: camera:latest
    build:
      context: .
      dockerfile: ./camera.dockerfile
    environment:
      RMQ_URI: 'amqp://guest:guest@rmq:5672/guest'
    depends_on:
      - rmq

  monitor:
    image: monitor:latest
    build:
      context: .
      dockerfile: ./monitor.dockerfile
    environment:
      RMQ_URI: 'amqp://guest:guest@rmq:5672/guest'
    depends_on:
      - rmq

#  climate:
#    image: climate
#    build:
#      context: .
#      dockerfile: ./climate.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  core:
#    image: core
#    build:
#      context: .
#      dockerfile: ./core.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  disease_detector:
#    image: disease_detector
#    build:
#      context: .
#      dockerfile: ./disease_detector.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  hardware_manager:
#    image: hardware_manager
#    build:
#      context: .
#      dockerfile: ./hardware_manager.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  irrigation_controller:
#    image: irrigation_controller
#    build:
#      context: .
#      dockerfile: ./irrigation_controller.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  irrigator:
#    image: irrigator
#    build:
#      context: .
#      dockerfile: ./irrigator.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
#  sensor:
#    image: sensor
#    build:
#      context: .
#      dockerfile: ./sensor.dockerfile
#    environment:
#      RMQ_URI: 'amqp://rmq'
#    depends_on:
#      - rmq
#
